server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_schema: kitchens
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          json_format_mapper: jackson
        jdbc:
          time_zone: UTC

  kafka:
    # Указываем адреса всех брокеров kafka
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

logging:
  exception-conversion-word: clr
  level:
    root: INFO
    by.pilipuk: INFO
    org.springframework.kafka: ERROR
    org.apache.kafka: ERROR
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){magenta} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"